### ISSUE TITLE
Flask-Restx and swagger-conformance

### ISSUE THREAD

**Issue by MartinThoma** [olipratt/swagger-conformance#12]
I generate my Swagger with [flask-restx](https://github.com/python-restx/flask-restx) and I wondered if there is any benefit to use swagger-conformance then. I it possible with flask-restx to not be conformant to the generated swagger?

If it provides value, is there anything special how to use them together?

**Comment by Stranger6667** [comment]
Hi Martin!
As the author of [a project](https://github.com/schemathesis/schemathesis) inspired by `swagger-conformance`, I'd like to note that schemas generated by libraries/frameworks like `flask-restx`, `fastapi`, `flasgger`, `grapeswagger`, etc. may contain errors. The concrete example of an erroneous schema generated with `flask-restx` was in [this repo](https://github.com/packit/packit-service/blob/398d0d20060ea3af92d21d9dab9b3adef599f365/packit_service/service/api/projects.py#L24) (relevant [comment](https://github.com/packit/packit-service/issues/368#issuecomment-668556357) on this bug). Generally speaking, tools like `flask-restx` still can't guarantee that the application behaves in conformance with its schema, e.g., that it won't fail with a server error, because the server-side handlers may contain arbitrary code. Therefore testing for API conformance is relevant for such apps, especially if it includes a wider range of checks (as in [Schemathesis](https://github.com/schemathesis/schemathesis) or [REST-ler](https://github.com/microsoft/restler-fuzzer) for example). There is very little research on how generated schemas are affected by such errors, but they are possible for sure.

**Comment by MartinThoma** [comment]
@Stranger6667 Thank you very much for the explanation!
